import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
// 	title: "ClimateAi: Graph Demo",
// 	description: "Generated by create next app",
// };

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<title>ClimateAi: Some Demos</title>
				<link
					href="https://unpkg.com/maplibre-gl@4.3.2/dist/maplibre-gl.css"
					rel="stylesheet"
				/>
			</head>
			<body className={`${inter.className} min-h-[100vh]`}>
				<div className="flex flex-col min-h-[100vh]">
					<nav className="bg-[#1c4756] text-white p-4">
						<a className="inline-block mr-4" href="/">
							<strong>ClimateAi</strong>
						</a>

						<ul className="inline-block">
							<li>
								<a href="/map">Map</a>
							</li>
						</ul>
					</nav>
					<div className="flex-1">{children}</div>
				</div>
				<Toaster />
			</body>
		</html>
	);
}
